version: "3"
services:
  api:
    build: .
    volumes:
      - /home/hawk/temp_ledger/ledger.dock:/app/ledger.dock
    ports:
      - 8080:8080
    environment:
      - LEDGER_FILE_DEV=/app/ledger.dock
